/******************************************************************************
 *
 * Copyright(c) 2019 Realtek Corporation. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of version 2 of the GNU General Public License as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
 * more details.
 *
 ******************************************************************************/

#ifndef _MAC_BE_SER_AUTO_GEN_8852C_H_
#define _MAC_BE_SER_AUTO_GEN_8852C_H_

#include "../../../../mac_ax/trxcfg.h"
#include "../../../../mac_ax/fwofld.h"
#if MAC_AX_8852C_SUPPORT

// svn reversion
#define SER_IMR_REV_8852C 39736

#define IMR_IO_OFLD_NON_FLUSH	0

#define SER_ENABLE 0XFFFFFFFF
#define SER_DISABLE 0X00000000

/* cmac_dma_top 0x1860c804 R_AX_RX_ERR_FLAG_IMR  */
/* cmac_dma_top 0x1860e804 R_AX_RX_ERR_FLAG_IMR_C1  */
#define CMAC_DMA_TOP_IMR0_MSK_8852C 0x7fffff06
#define CMAC_DMA_TOP_IMR0_SET_8852C 0x7fffff06
// Enable Bit, rxsts_enque_error_imr, B_AX_RXSTS_ENQUE_ORDER_ERR
#define CMAC_DMA_TOP_IMR0_BIT1_8852C_EN SER_ENABLE
// Enable Bit, rxdata_enque_error_imr, B_AX_RXDATA_ENQUE_ORDER_ERR
#define CMAC_DMA_TOP_IMR0_BIT2_8852C_EN SER_ENABLE
// Enable Bit, csi_zero_len_imr, B_AX_RX_CSI_ZERO_LEN_ERR
#define CMAC_DMA_TOP_IMR0_BIT8_8852C_EN SER_ENABLE
// Enable Bit, rxsts_zero_len_imr, B_AX_RX_RXSTS_ZERO_LEN_ERR
#define CMAC_DMA_TOP_IMR0_BIT9_8852C_EN SER_ENABLE
// Enable Bit, ru7_zero_len_imr, B_AX_RX_RU7_ZERO_LEN_ERR
#define CMAC_DMA_TOP_IMR0_BIT10_8852C_EN SER_ENABLE
// Enable Bit, ru6_zero_len_imr, B_AX_RX_RU6_ZERO_LEN_ERR
#define CMAC_DMA_TOP_IMR0_BIT11_8852C_EN SER_ENABLE
// Enable Bit, ru5_zero_len_imr, B_AX_RX_RU5_ZERO_LEN_ERR
#define CMAC_DMA_TOP_IMR0_BIT12_8852C_EN SER_ENABLE
// Enable Bit, ru4_zero_len_imr, B_AX_RX_RU4_ZERO_LEN_ERR
#define CMAC_DMA_TOP_IMR0_BIT13_8852C_EN SER_ENABLE
// Enable Bit, ru3_zero_len_imr, B_AX_RX_RU3_ZERO_LEN_ERR
#define CMAC_DMA_TOP_IMR0_BIT14_8852C_EN SER_ENABLE
// Enable Bit, ru2_zero_len_imr, B_AX_RX_RU2_ZERO_LEN_ERR
#define CMAC_DMA_TOP_IMR0_BIT15_8852C_EN SER_ENABLE
// Enable Bit, ru1_zero_len_imr, B_AX_RX_RU1_ZERO_LEN_ERR
#define CMAC_DMA_TOP_IMR0_BIT16_8852C_EN SER_ENABLE
// Enable Bit, ru0_zero_len_imr, B_AX_RX_RU0_ZERO_LEN_ERR
#define CMAC_DMA_TOP_IMR0_BIT17_8852C_EN SER_ENABLE
// Enable Bit, f2pcmd_fsm_hang_imr, B_AX_RX_F2PCMD_FSM_HANG_ERR
#define CMAC_DMA_TOP_IMR0_BIT18_8852C_EN SER_ENABLE
// Enable Bit, txrpt_fsm_hang_imr, B_AX_RX_TXRPT_FSM_HANG_ERR
#define CMAC_DMA_TOP_IMR0_BIT19_8852C_EN SER_ENABLE
// Enable Bit, csi_fsm_hang_imr, B_AX_RX_CSI_FSM_HANG_ERR
#define CMAC_DMA_TOP_IMR0_BIT20_8852C_EN SER_ENABLE
// Enable Bit, rxsts_fsm_hang_imr, B_AX_RX_RXSTS_FSM_HANG_ERR
#define CMAC_DMA_TOP_IMR0_BIT21_8852C_EN SER_ENABLE
// Enable Bit, ru7_fsm_hang_imr, B_AX_RX_RU7_FSM_HANG_ERR
#define CMAC_DMA_TOP_IMR0_BIT22_8852C_EN SER_ENABLE
// Enable Bit, ru6_fsm_hang_imr, B_AX_RX_RU6_FSM_HANG_ERR
#define CMAC_DMA_TOP_IMR0_BIT23_8852C_EN SER_ENABLE
// Enable Bit, ru5_fsm_hang_imr, B_AX_RX_RU5_FSM_HANG_ERR
#define CMAC_DMA_TOP_IMR0_BIT24_8852C_EN SER_ENABLE
// Enable Bit, ru4_fsm_hang_imr, B_AX_RX_RU4_FSM_HANG_ERR
#define CMAC_DMA_TOP_IMR0_BIT25_8852C_EN SER_ENABLE
// Enable Bit, ru3_fsm_hang_imr, B_AX_RX_RU3_FSM_HANG_ERR
#define CMAC_DMA_TOP_IMR0_BIT26_8852C_EN SER_ENABLE
// Enable Bit, ru2_fsm_hang_imr, B_AX_RX_RU2_FSM_HANG_ERR
#define CMAC_DMA_TOP_IMR0_BIT27_8852C_EN SER_ENABLE
// Enable Bit, ru1_fsm_hang_imr, B_AX_RX_RU1_FSM_HANG_ERR
#define CMAC_DMA_TOP_IMR0_BIT28_8852C_EN SER_ENABLE
// Enable Bit, ru0_fsm_hang_imr, B_AX_RX_RU0_FSM_HANG_ERR
#define CMAC_DMA_TOP_IMR0_BIT29_8852C_EN SER_ENABLE
// Enable Bit, rx_get_null_pkt_imr, B_AX_RX_GET_NULL_PKT_ERR
#define CMAC_DMA_TOP_IMR0_BIT30_8852C_EN SER_ENABLE
/* cmac_dma_top 0x1860c870 R_AX_TX_ERR_FLAG_IMR  */
/* cmac_dma_top 0x1860e870 R_AX_TX_ERR_FLAG_IMR_C1  */
#define CMAC_DMA_TOP_IMR1_MSK_8852C 0xff00c000
#define CMAC_DMA_TOP_IMR1_SET_8852C 0xff00c000
// Enable Bit, tx_get_pld_fsm_hang_imr, B_AX_TX_WD_PLD_ID_FSM_HANG_ERR
#define CMAC_DMA_TOP_IMR1_BIT14_8852C_EN SER_ENABLE
// Enable Bit, csi_fsm_hang_imr, B_AX_TX_CSI_FSM_HANG_ERR
#define CMAC_DMA_TOP_IMR1_BIT15_8852C_EN SER_ENABLE
// Enable Bit, ru7_fsm_hang_imr, B_AX_TX_RU7_FSM_HANG_ERR
#define CMAC_DMA_TOP_IMR1_BIT24_8852C_EN SER_ENABLE
// Enable Bit, ru6_fsm_hang_imr, B_AX_TX_RU6_FSM_HANG_ERR
#define CMAC_DMA_TOP_IMR1_BIT25_8852C_EN SER_ENABLE
// Enable Bit, ru5_fsm_hang_imr, B_AX_TX_RU5_FSM_HANG_ERR
#define CMAC_DMA_TOP_IMR1_BIT26_8852C_EN SER_ENABLE
// Enable Bit, ru4_fsm_hang_imr, B_AX_TX_RU4_FSM_HANG_ERR
#define CMAC_DMA_TOP_IMR1_BIT27_8852C_EN SER_ENABLE
// Enable Bit, ru3_fsm_hang_imr, B_AX_TX_RU3_FSM_HANG_ERR
#define CMAC_DMA_TOP_IMR1_BIT28_8852C_EN SER_ENABLE
// Enable Bit, ru2_fsm_hang_imr, B_AX_TX_RU2_FSM_HANG_ERR
#define CMAC_DMA_TOP_IMR1_BIT29_8852C_EN SER_ENABLE
// Enable Bit, ru1_fsm_hang_imr, B_AX_TX_RU1_FSM_HANG_ERR
#define CMAC_DMA_TOP_IMR1_BIT30_8852C_EN SER_ENABLE
// Enable Bit, ru0_fsm_hang_imr, B_AX_TX_RU0_FSM_HANG_ERR
#define CMAC_DMA_TOP_IMR1_BIT31_8852C_EN SER_ENABLE
/* ptcltop 0x1860c6c0 R_AX_PTCL_IMR0  */
/* ptcltop 0x1860e6c0 R_AX_PTCL_IMR0_C1  */
#define PTCLTOP_IMR0_MSK_8852C 0x3
#define PTCLTOP_IMR0_SET_8852C 0x3
// Enable Bit, fsm_timeout_err_imr, B_AX_FSM_TIMEOUT_ERR
#define PTCLTOP_IMR0_BIT0_8852C_EN SER_ENABLE
// Enable Bit, fsm1_timeout_err_imr, None
#define PTCLTOP_IMR0_BIT1_8852C_EN SER_ENABLE
/* schedulertop 0x1860c3e8 R_AX_SCHEDULE_ERR_IMR  */
/* schedulertop 0x1860e3e8 R_AX_SCHEDULE_ERR_IMR_C1  */
#define SCHEDULERTOP_IMR0_MSK_8852C 0x3
#define SCHEDULERTOP_IMR0_SET_8852C 0x1
// Enable Bit, fsm_timeout_err_imr, B_AX_FSM_TIMEOUT_ERR_INT
#define SCHEDULERTOP_IMR0_BIT0_8852C_EN SER_ENABLE
// Enable Bit, sort_non_idle_err_imr, B_AX_SORT_NON_IDLE_ERR_INT
#define SCHEDULERTOP_IMR0_BIT1_8852C_EN SER_DISABLE
/* phyintf 0x1860ccf8 R_AX_PHYINFO_ERR_IMR_V1  */
/* phyintf 0x1860ecf8 R_AX_PHYINFO_ERR_IMR_V1_C1  */
#define PHYINTF_IMR0_MSK_8852C 0x3f
#define PHYINTF_IMR0_SET_8852C 0x31
// Enable Bit, phy_txon timeout_err_imr, B_AX_PHY_TXON_TIMEOUT_ERR
#define PHYINTF_IMR0_BIT0_8852C_EN SER_ENABLE
// Enable Bit, cck_cca timeout_errr_imr, B_AX_CCK_CCA_TIMEOUT_ERR
#define PHYINTF_IMR0_BIT1_8852C_EN SER_DISABLE
// Enable Bit, ofdm_cca timeout_errr_imr, B_AX_OFDM_CCA_TIMEOUT_ERR
#define PHYINTF_IMR0_BIT2_8852C_EN SER_DISABLE
// Enable Bit, data_on timeout_errr_imr, B_AX_DATA_ON_TIMEOUT_ERR
#define PHYINTF_IMR0_BIT3_8852C_EN SER_DISABLE
// Enable Bit, sts_on timeout_errr_imr, B_AX_STS_ON_TIMEOUT_ERR
#define PHYINTF_IMR0_BIT4_8852C_EN SER_ENABLE
// Enable Bit, csi_on timeout_errr_imr, B_AX_CSI_ON_TIMEOUT_ERR
#define PHYINTF_IMR0_BIT5_8852C_EN SER_ENABLE
/* rmac 0x1860cef8 R_AX_RX_ERR_IMR  */
/* rmac 0x1860eef8 R_AX_RX_ERR_IMR_C1  */
#define RMAC_IMR0_MSK_8852C 0x3ff
#define RMAC_IMR0_SET_8852C 0x3d8
// Enable Bit, cca to rx idle time out_imr, B_AX_RX_ERR_CCA_TO
#define RMAC_IMR0_BIT0_8852C_EN SER_DISABLE
// Enable Bit, data_on to rx idle time out_imr, B_AX_RX_ERR_DATA_TO
#define RMAC_IMR0_BIT1_8852C_EN SER_DISABLE
// Enable Bit, dma write time out_imr, B_AX_RX_ERR_DMA_TO
#define RMAC_IMR0_BIT2_8852C_EN SER_DISABLE
// Enable Bit, cca time out_imr, B_AX_CCA_ASSERT_TO
#define RMAC_IMR0_BIT3_8852C_EN SER_ENABLE
// Enable Bit, data_on time out_imr, B_AX_DATAON_ASSERT_TO
#define RMAC_IMR0_BIT4_8852C_EN SER_ENABLE
// Enable Bit, csi_data_on time out_imr, B_AX_CSI_DATAON_ASSERT_TO
#define RMAC_IMR0_BIT5_8852C_EN SER_DISABLE
// Enable Bit, rx FSM time out_imr, B_AX_RX_ERR_ACT_TO
#define RMAC_IMR0_BIT6_8852C_EN SER_ENABLE
// Enable Bit, rx CSI mode time out_imr, B_AX_RX_ERR_CSI_ACT_TO
#define RMAC_IMR0_BIT7_8852C_EN SER_ENABLE
// Enable Bit, rx ppdu status FSM time out_imr, B_AX_RX_ERR_STS_ACT_TO
#define RMAC_IMR0_BIT8_8852C_EN SER_ENABLE
// Enable Bit, rx trigger FSM time out_imr, B_AX_RX_ERR_TRIG_ACT_TO
#define RMAC_IMR0_BIT9_8852C_EN SER_ENABLE
/* tmac 0x1860ccbc R_AX_TRXPTCL_ERROR_INDICA_MASK  */
/* tmac 0x1860ecbc R_AX_TRXPTCL_ERROR_INDICA_MASK_C1  */
#define TMAC_IMR0_MSK_8852C 0x1ff
#define TMAC_IMR0_SET_8852C 0x17f
// Enable Bit, mactx timeout_errr_imr, B_AX_MACTX_ERROR_FLAG_CLR
#define TMAC_IMR0_BIT0_8852C_EN SER_ENABLE
// Enable Bit, trxptcl txctl timeout_errr_imr, B_AX_TXCTL_ERROR_FLAG_CLR
#define TMAC_IMR0_BIT1_8852C_EN SER_ENABLE
// Enable Bit, response txctl timeout_errr_imr, B_AX_RESP_ERROR_FLAG_CLR
#define TMAC_IMR0_BIT2_8852C_EN SER_ENABLE
// Enable Bit, tx plcp info errr_imr, B_AX_TXPLCP_ERROR_FLAG_CLR
#define TMAC_IMR0_BIT3_8852C_EN SER_ENABLE
// Enable Bit, hw sigb gen errr_imr, B_AX_HWSIGB_GEN_ERROR_FLAG_CLR
#define TMAC_IMR0_BIT4_8852C_EN SER_ENABLE
// Enable Bit, rxtb control errr_imr, B_AX_RXTB_ERROR_FLAG_CLR
#define TMAC_IMR0_BIT5_8852C_EN SER_ENABLE
// Enable Bit, mimo control errr_imr, B_AX_MIMOCTRL_ERROR_FLAG_CLR
#define TMAC_IMR0_BIT6_8852C_EN SER_ENABLE
// Enable Bit, csi control errr_imr, B_AX_CSI_ERROR_FLAG_CLR
#define TMAC_IMR0_BIT7_8852C_EN SER_DISABLE
// Enable Bit, ftm control errr_imr, B_AX_FTM_ERROR_FLAG_CLR
#define TMAC_IMR0_BIT8_8852C_EN SER_ENABLE
/* STA scheduler 0x18609ef0 R_AX_STA_SCHEDULER_ERR_IMR  */
#define STA_SCHEDULER_IMR0_MSK_8852C 0x7
#define STA_SCHEDULER_IMR0_SET_8852C 0x7
// Enable Bit, search hang timeout IMR, B_AX_SEARCH_HANG_TIMEOUT_ISR
#define STA_SCHEDULER_IMR0_BIT0_8852C_EN SER_ENABLE
// Enable Bit, report hang timeout IMR, B_AX_RPT_HANG_TIMEOUT_ISR
#define STA_SCHEDULER_IMR0_BIT1_8852C_EN SER_ENABLE
// Enable Bit, ple_b_pktid_err_IMR, B_AX_PLE_B_PKTID_ERR_ISR
#define STA_SCHEDULER_IMR0_BIT2_8852C_EN SER_ENABLE
/* MPDU TX Processor 0x18609bf4 R_AX_MPDU_TX_ERR_IMR  */
#define MPDU_TX_PROCESSOR_IMR0_MSK_8852C 0x3fe
#define MPDU_TX_PROCESSOR_IMR0_SET_8852C 0x36e
// Enable Bit, get null packet ID IMR, B_AX_TX_GET_ERRPKTID_ERR
#define MPDU_TX_PROCESSOR_IMR0_BIT1_8852C_EN SER_ENABLE
// Enable Bit, get null packet ID in STF mode IMR, B_AX_TX_NXT_ERRPKTID_ERR
#define MPDU_TX_PROCESSOR_IMR0_BIT2_8852C_EN SER_ENABLE
// Enable Bit, zero msdu length IMR, B_AX_TX_MPDU_SIZE_ZERO_ERR
#define MPDU_TX_PROCESSOR_IMR0_BIT3_8852C_EN SER_ENABLE
// Enable Bit, illegal offset IMR, B_AX_TX_OFFSET_ERR
#define MPDU_TX_PROCESSOR_IMR0_BIT4_8852C_EN SER_DISABLE
// Enable Bit, illegal ethernet header length IMR, B_AX_TX_HDR3_SIZE_ERR
#define MPDU_TX_PROCESSOR_IMR0_BIT5_8852C_EN SER_ENABLE
// Enable Bit, ether type error IMR, B_AX_TX_ETH_TYPE_ERR
#define MPDU_TX_PROCESSOR_IMR0_BIT6_8852C_EN SER_ENABLE
// Enable Bit, llc[31:0] error IMR, B_AX_TX_LLC_PRE_ERR
#define MPDU_TX_PROCESSOR_IMR0_BIT7_8852C_EN SER_DISABLE
// Enable Bit, network type error IMR, B_AX_TX_NW_TYPE_ERR
#define MPDU_TX_PROCESSOR_IMR0_BIT8_8852C_EN SER_ENABLE
// Enable Bit, key search fail IMR, B_AX_TX_KSRCH_ERR
#define MPDU_TX_PROCESSOR_IMR0_BIT9_8852C_EN SER_ENABLE
/* MPDU RX Processor 0x18609cf4 R_AX_MPDU_RX_ERR_IMR  */
#define MPDU_RX_PROCESSOR_IMR0_MSK_8852C 0x3
#define MPDU_RX_PROCESSOR_IMR0_SET_8852C 0x0
// Enable Bit, get null packet ID IMR, B_AX_GETPKTID_ERR_ISR
#define MPDU_RX_PROCESSOR_IMR0_BIT0_8852C_EN SER_DISABLE
// Enable Bit, RX_TIMEOUT_ERR_IMR, None
#define MPDU_RX_PROCESSOR_IMR0_BIT1_8852C_EN SER_DISABLE
/* WSEC 0x18609d2c R_AX_SEC_ERROR_FLAG_IMR  */
#define WSEC_IMR0_MSK_8852C 0x3
#define WSEC_IMR0_SET_8852C 0x3
// Enable Bit, Tx timeout IMR, B_AX_TX_HANG_ERROR_V1
#define WSEC_IMR0_BIT0_8852C_EN SER_ENABLE
// Enable Bit, Rx timeout IMR, B_AX_RX_HANG_ERROR_V1
#define WSEC_IMR0_BIT1_8852C_EN SER_ENABLE
/* PKTIN 0x18609a20 R_AX_PKTIN_ERR_IMR  */
#define PKTIN_IMR0_MSK_8852C 0x1
#define PKTIN_IMR0_SET_8852C 0x1
// Enable Bit,  get null pktid IMR, B_AX_PKTIN_GETPKTID_ERR_INT
#define PKTIN_IMR0_BIT0_8852C_EN SER_ENABLE
/* Host Dispatcher 0x18608850 R_AX_HOST_DISPATCHER_ERR_IMR  */
#define HOST_DISPATCHER_IMR0_MSK_8852C 0xffd7ffff
#define HOST_DISPATCHER_IMR0_SET_8852C 0xc100060
// Enable Bit, B_AX_HT_EP_CH_DIFF_ERR_IMR, B_AX_HT_EP_CH_DIFF_ERR
#define HOST_DISPATCHER_IMR0_BIT0_8852C_EN SER_DISABLE
// Enable Bit, B_AX_HT_CH_ID_ERR_IMR, B_AX_HT_CH_ID_ERR
#define HOST_DISPATCHER_IMR0_BIT1_8852C_EN SER_DISABLE
// Enable Bit, B_AX_HT_PKT_FAIL_ERR_IMR, B_AX_HT_PKT_FAIL_ERR
#define HOST_DISPATCHER_IMR0_BIT2_8852C_EN SER_DISABLE
// Enable Bit, B_AX_HT_PERMU_FF_OVERFLOW_ERR_IMR, B_AX_HT_PERMU_FF_OVERFLOW_ERR
#define HOST_DISPATCHER_IMR0_BIT3_8852C_EN SER_DISABLE
// Enable Bit, B_AX_HT_PERMU_FF_UNDERFLOW_ERR_IMR, B_AX_HT_PERMU_FF_UNDERFLOW_ERR
#define HOST_DISPATCHER_IMR0_BIT4_8852C_EN SER_DISABLE
// Enable Bit, B_AX_HT_PAYLOAD_OVER_ERR_IMR, B_AX_HT_PAYLOAD_OVER_ERR
#define HOST_DISPATCHER_IMR0_BIT5_8852C_EN SER_ENABLE
// Enable Bit, B_AX_HT_PAYLOAD_UNDER_ERR_IMR, B_AX_HT_PAYLOAD_UNDER_ERR
#define HOST_DISPATCHER_IMR0_BIT6_8852C_EN SER_ENABLE
// Enable Bit, B_AX_HT_OFFSET_UNMATCH_ERR_IMR, B_AX_HT_OFFSET_UNMATCH_ERR
#define HOST_DISPATCHER_IMR0_BIT7_8852C_EN SER_DISABLE
// Enable Bit, B_AX_HT_CHANNEL_DMA_ERR_IMR, B_AX_HT_CHANNEL_DMA_ERR
#define HOST_DISPATCHER_IMR0_BIT8_8852C_EN SER_DISABLE
// Enable Bit, B_AX_HT_WD_CHKSUM_ERR_IMR, B_AX_HT_WD_CHKSUM_ERR
#define HOST_DISPATCHER_IMR0_BIT9_8852C_EN SER_DISABLE
// Enable Bit, B_AX_HT_PRE_SUB_ERR_IMR, B_AX_HT_PRE_SUB_ERR
#define HOST_DISPATCHER_IMR0_BIT10_8852C_EN SER_DISABLE
// Enable Bit, B_AX_HT_TXPKTSIZE_ERR_IMR, B_AX_HT_TXPKTSIZE_ERR
#define HOST_DISPATCHER_IMR0_BIT11_8852C_EN SER_DISABLE
// Enable Bit, B_AX_HT_CHKSUM_FSM_ERR_IMR, B_AX_HT_CHKSUM_FSM_ERR
#define HOST_DISPATCHER_IMR0_BIT12_8852C_EN SER_DISABLE
// Enable Bit, B_AX_HT_WRFF_OVERFLOW_ERR_IMR, B_AX_HT_WRFF_OVERFLOW_ERR
#define HOST_DISPATCHER_IMR0_BIT13_8852C_EN SER_DISABLE
// Enable Bit, B_AX_HT_WRFF_UNDERFLOW_ERR_IMR, B_AX_HT_WRFF_UNDERFLOW_ERR
#define HOST_DISPATCHER_IMR0_BIT14_8852C_EN SER_DISABLE
// Enable Bit, B_AX_HT_PLD_CMD_OVERFLOW_ERR_IMR, B_AX_HT_PLD_CMD_OVERFLOW_ERR
#define HOST_DISPATCHER_IMR0_BIT15_8852C_EN SER_DISABLE
// Enable Bit, B_AX_HT_PLD_CMD_UNDERFLOW_ERR_IMR, B_AX_HT_PLD_CMD_UNDERFLOW_ERR
#define HOST_DISPATCHER_IMR0_BIT16_8852C_EN SER_DISABLE
// Enable Bit, B_AX_HT_WD_LEN_OVER_ERR_IMR, B_AX_HT_WD_LEN_OVER_ERR
#define HOST_DISPATCHER_IMR0_BIT17_8852C_EN SER_DISABLE
// Enable Bit, B_AX_HT_ADDR_INFO_LEN_ERR_IMR, B_AX_HT_ADDR_INFO_LEN_ERR
#define HOST_DISPATCHER_IMR0_BIT18_8852C_EN SER_DISABLE
// Enable Bit, B_AX_HT_ILL_CH_ERR_IMR, B_AX_HT_ILL_CH_ERR
#define HOST_DISPATCHER_IMR0_BIT20_8852C_EN SER_ENABLE
// Enable Bit, B_HR_PLD_LEN_ZERO_ERR_IMR, B_AX_HR_PLD_LEN_ZERO_ERR
#define HOST_DISPATCHER_IMR0_BIT22_8852C_EN SER_DISABLE
// Enable Bit, B_HR_DMA_RD_CNT_DEQ_ERR_IMR, B_AX_HR_DMA_RD_CNT_DEQ_ERR
#define HOST_DISPATCHER_IMR0_BIT23_8852C_EN SER_DISABLE
// Enable Bit, B_HR_AGG_CFG_ERR_IMR, B_AX_HR_AGG_CFG_ERR
#define HOST_DISPATCHER_IMR0_BIT24_8852C_EN SER_DISABLE
// Enable Bit, B_HR_SHIFT_EN_ERR_IMR, B_AX_HR_SHIFT_EN_ERR
#define HOST_DISPATCHER_IMR0_BIT25_8852C_EN SER_DISABLE
// Enable Bit, B_HR_TOTAL_LEN_UNDER_ERR_IMR, B_AX_HR_TOTAL_LEN_UNDER_ERR
#define HOST_DISPATCHER_IMR0_BIT26_8852C_EN SER_ENABLE
// Enable Bit, B_HR_DMA_PROCESS_ERR_IMR, B_AX_HR_DMA_PROCESS_ERR
#define HOST_DISPATCHER_IMR0_BIT27_8852C_EN SER_ENABLE
// Enable Bit, B_HR_SHIFT_DMA_CFG_ERR_IMR, B_AX_HR_SHIFT_DMA_CFG_ERR
#define HOST_DISPATCHER_IMR0_BIT28_8852C_EN SER_DISABLE
// Enable Bit, B_HR_CHKSUM_FSM_ERR_IMR, B_AX_HR_CHKSUM_FSM_ERR
#define HOST_DISPATCHER_IMR0_BIT29_8852C_EN SER_DISABLE
// Enable Bit, B_HR_WRFF_OVERFLOW_ERR_IMR, B_AX_HR_WRFF_OVERFLOW_ERR
#define HOST_DISPATCHER_IMR0_BIT30_8852C_EN SER_DISABLE
// Enable Bit, B_HR_WRFF_UNDERFLOW_ERR_IMR, B_AX_HR_WRFF_UNDERFLOW_ERR
#define HOST_DISPATCHER_IMR0_BIT31_8852C_EN SER_DISABLE
/* CPU Dispatcher 0x18608854 R_AX_CPU_DISPATCHER_ERR_IMR  */
#define CPU_DISPATCHER_IMR0_MSK_8852C 0x7f7bfffd
#define CPU_DISPATCHER_IMR0_SET_8852C 0x36000060
// Enable Bit, B_AX_CT_EP_CH_DIFF_ERR_IMR, B_AX_CT_EP_CH_DIFF_ERR
#define CPU_DISPATCHER_IMR0_BIT0_8852C_EN SER_DISABLE
// Enable Bit, B_AX_CT_CH_ID_ERR_IMR, B_AX_CT_CH_ID_ERR
#define CPU_DISPATCHER_IMR0_BIT2_8852C_EN SER_DISABLE
// Enable Bit, B_AX_CT_PERMU_FF_OVERFLOW_ERR_IMR, B_AX_CT_PERMU_FF_OVERFLOW_ERR
#define CPU_DISPATCHER_IMR0_BIT3_8852C_EN SER_DISABLE
// Enable Bit, B_AX_CT_PERMU_FF_UNDERFLOW_ERR_IMR, B_AX_CT_PERMU_FF_UNDERFLOW_ERR
#define CPU_DISPATCHER_IMR0_BIT4_8852C_EN SER_DISABLE
// Enable Bit, B_AX_CT_PAYLOAD_OVER_ERR_IMR, B_AX_CT_PAYLOAD_OVER_ERR
#define CPU_DISPATCHER_IMR0_BIT5_8852C_EN SER_ENABLE
// Enable Bit, B_AX_CT_PAYLOAD_UNDER_ERR_IMR, B_AX_CT_PAYLOAD_UNDER_ERR
#define CPU_DISPATCHER_IMR0_BIT6_8852C_EN SER_ENABLE
// Enable Bit, B_AX_CT_PAYLOAD_CHKSUM_ERR_IMR, B_AX_CT_PAYLOAD_CHKSUM_ERR
#define CPU_DISPATCHER_IMR0_BIT7_8852C_EN SER_DISABLE
// Enable Bit, B_AX_CT_OFFSET_UNMATCH_ERR_IMR, B_AX_CT_OFFSET_UNMATCH_ERR
#define CPU_DISPATCHER_IMR0_BIT8_8852C_EN SER_DISABLE
// Enable Bit, B_AX_CT_CHANNEL_DMA_ERR_IMR, B_AX_CT_CHANNEL_DMA_ERR
#define CPU_DISPATCHER_IMR0_BIT9_8852C_EN SER_DISABLE
// Enable Bit, B_AX_CT_WD_CHKSUM_ERR_IMR, B_AX_CT_WD_CHKSUM_ERR
#define CPU_DISPATCHER_IMR0_BIT10_8852C_EN SER_DISABLE
// Enable Bit, B_AX_CT_PRE_SUB_ERR_IMR, B_AX_CT_PRE_SUB_ERR
#define CPU_DISPATCHER_IMR0_BIT11_8852C_EN SER_DISABLE
// Enable Bit, B_AX_CT_PLD_CMD_OVERFLOW_ERR_IMR, B_AX_CT_PLD_CMD_OVERFLOW_ERR
#define CPU_DISPATCHER_IMR0_BIT12_8852C_EN SER_DISABLE
// Enable Bit, B_AX_CT_PLD_CMD_UNDERFLOW_ERR_IMR, B_AX_CT_PLD_CMD_UNDERFLOW_ERR
#define CPU_DISPATCHER_IMR0_BIT13_8852C_EN SER_DISABLE
// Enable Bit, B_AX_CT_F2P_QSEL_ERR_IMR, B_AX_CT_F2P_QSEL_ERR
#define CPU_DISPATCHER_IMR0_BIT14_8852C_EN SER_DISABLE
// Enable Bit, B_AX_CT_F2P_SEQ_ERR_IMR, B_AX_CT_F2P_SEQ_ERR
#define CPU_DISPATCHER_IMR0_BIT15_8852C_EN SER_DISABLE
// Enable Bit, B_AX_CT_WD_LEN_OVER_ERR_IMR, B_AX_CT_WD_LEN_OVER_ERR
#define CPU_DISPATCHER_IMR0_BIT16_8852C_EN SER_DISABLE
// Enable Bit, B_AX_CT_ADDR_INFO_LEN_MISS_ERR_IMR, B_AX_CT_ADDR_INFO_LEN_MISS_ERR
#define CPU_DISPATCHER_IMR0_BIT17_8852C_EN SER_DISABLE
// Enable Bit, B_AX_REUSE_FIFO_A_OVER_ERR_IMR, B_AX_REUSE_FIFO_A_OVER_ERR
#define CPU_DISPATCHER_IMR0_BIT19_8852C_EN SER_DISABLE
// Enable Bit, B_AX_REUSE_FIFO_A_UNDER_ERR_IMR, B_AX_REUSE_FIFO_A_UNDER_ERR
#define CPU_DISPATCHER_IMR0_BIT20_8852C_EN SER_DISABLE
// Enable Bit, B_AX_REUSE_FIFO_B_OVER_ERR_IMR, B_AX_REUSE_FIFO_B_OVER_ERR
#define CPU_DISPATCHER_IMR0_BIT21_8852C_EN SER_DISABLE
// Enable Bit, B_AX_REUSE_FIFO_B_UNDER_ERR_IMR, B_AX_REUSE_FIFO_B_UNDER_ERR
#define CPU_DISPATCHER_IMR0_BIT22_8852C_EN SER_DISABLE
// Enable Bit, B_AX_CR_SHIFT_EN_ERR_IMR, B_AX_CR_SHIFT_EN_ERR
#define CPU_DISPATCHER_IMR0_BIT24_8852C_EN SER_DISABLE
// Enable Bit, B_AX_CR_TOTAL_LEN_UNDER_ERR_IMR, B_AX_CR_TOTAL_LEN_UNDER_ERR
#define CPU_DISPATCHER_IMR0_BIT25_8852C_EN SER_ENABLE
// Enable Bit, B_AX_CR_DMA_PROCESS_ERR_IMR, B_AX_CR_DMA_PROCESS_ERR
#define CPU_DISPATCHER_IMR0_BIT26_8852C_EN SER_ENABLE
// Enable Bit, B_AX_CR_SHIFT_DMA_CFG_ERR_IMR, B_AX_CR_SHIFT_DMA_CFG_ERR
#define CPU_DISPATCHER_IMR0_BIT27_8852C_EN SER_DISABLE
// Enable Bit, B_AX_CR_WRFF_OVERFLOW_ERR_IMR, B_AX_CR_WRFF_OVERFLOW_ERR
#define CPU_DISPATCHER_IMR0_BIT28_8852C_EN SER_ENABLE
// Enable Bit, B_AX_CR_WRFF_UNDERFLOW_ERR_IMR, B_AX_CR_WRFF_UNDERFLOW_ERR
#define CPU_DISPATCHER_IMR0_BIT29_8852C_EN SER_ENABLE
// Enable Bit, B_AX_CR_PLD_LEN_ERR_IMR, B_AX_CR_PLD_LEN_ERR
#define CPU_DISPATCHER_IMR0_BIT30_8852C_EN SER_DISABLE
/* Dispatcher DLE interface 0x18608858 R_AX_OTHER_DISPATCHER_ERR_IMR  */
#define DISPATCHER_DLE_INTERFACE_IMR0_MSK_8852C 0xffffdfdf
#define DISPATCHER_DLE_INTERFACE_IMR0_SET_8852C 0x303cc000
// Enable Bit, B_WDE_FLOW_CTRL_ERR_IMR, B_AX_WDE_FLOW_CTRL_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT0_8852C_EN SER_DISABLE
// Enable Bit, B_WDE_NULL_PKT_ERR_IMR, B_AX_WDE_NULL_PKT_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT1_8852C_EN SER_DISABLE
// Enable Bit, B_WDE_BURST_NUM_ERR_IMR, B_AX_WDE_BURST_NUM_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT2_8852C_EN SER_DISABLE
// Enable Bit, B_WDE_RESPONSE_ERR_IMR, B_AX_WDE_RESPONSE_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT3_8852C_EN SER_DISABLE
// Enable Bit, B_WDE_OUTPUT_ERR_IMR, B_AX_WDE_OUTPUT_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT4_8852C_EN SER_DISABLE
// Enable Bit, B_HDR_RX_TIMEOUT_ERR_IMR, B_AX_HDR_RX_TIMEOUT_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT6_8852C_EN SER_DISABLE
// Enable Bit, B_HDR_DMA_TIMEOUT_ERR_IMR, B_AX_HDR_DMA_TIMEOUT_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT7_8852C_EN SER_DISABLE
// Enable Bit, B_PLE_FLOW_CTRL_ERR_IMR, B_AX_PLE_FLOW_CTRL_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT8_8852C_EN SER_DISABLE
// Enable Bit, B_PLE_NULL_PKT_ERR_IMR, B_AX_PLE_NULL_PKT_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT9_8852C_EN SER_DISABLE
// Enable Bit, B_PLE_BURST_NUM_ERR_IMR, B_AX_PLE_BURST_NUM_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT10_8852C_EN SER_DISABLE
// Enable Bit, B_PLE_RESPOSE_ERR_IMR, B_AX_PLE_RESPOSE_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT11_8852C_EN SER_DISABLE
// Enable Bit, B_PLE_OUTPUT_ERR_IMR, B_AX_PLE_OUTPUT_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT12_8852C_EN SER_DISABLE
// Enable Bit, B_CDR_RX_TIMEOUT_ERR_IMR, B_AX_CDR_RX_TIMEOUT_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT14_8852C_EN SER_ENABLE
// Enable Bit, B_CDR_DMA_TIMEOUT_ERR_IMR, B_AX_CDR_DMA_TIMEOUT_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT15_8852C_EN SER_ENABLE
// Enable Bit, B_HDT_ADDR_INFO_LEN_ERR_IMR, B_AX_HDT_ADDR_INFO_LEN_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT16_8852C_EN SER_DISABLE
// Enable Bit, B_CDT_ADDR_INFO_LEN_ERR_IMR, B_AX_CDT_ADDR_INFO_LEN_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT17_8852C_EN SER_DISABLE
// Enable Bit, B_HDT_HCI_TIMEOUT_ERR_IMR, B_AX_HDT_HCI_TIMEOUT_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT18_8852C_EN SER_ENABLE
// Enable Bit, B_HDT_PTR_TIMEOUT_ERR_IMR, B_AX_HDT_PTR_TIMEOUT_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT19_8852C_EN SER_ENABLE
// Enable Bit, B_CDT_HCI_TIMEOUT_ERR_IMR, B_AX_CDT_HCI_TIMEOUT_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT20_8852C_EN SER_ENABLE
// Enable Bit, B_CDT_PTR_TIMEOUT_ERR_IMR, B_AX_CDT_PTR_TIMEOUT_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT21_8852C_EN SER_ENABLE
// Enable Bit, B_REUSE_PKT_CNT_ERR_IMR, B_AX_REUSE_PKT_CNT_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT22_8852C_EN SER_DISABLE
// Enable Bit, B_REUSE_SIZE_ZERO_ERR_IMR, B_AX_REUSE_SIZE_ZERO_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT23_8852C_EN SER_DISABLE
// Enable Bit, B_STF_CMD_OVERFLOW_ERR_IMR, B_AX_STF_CMD_OVERFLOW_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT24_8852C_EN SER_DISABLE
// Enable Bit, B_STF_CMD_UNDERFLOW_ERR_IMR, B_AX_STF_CMD_UNDERFLOW_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT25_8852C_EN SER_DISABLE
// Enable Bit, B_STF_WRFF_OVERFLOW_ERR_IMR, B_AX_STF_WRFF_OVERFLOW_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT26_8852C_EN SER_DISABLE
// Enable Bit, B_STF_WRFF_UNDERFLOW_ERR_IMR, B_AX_STF_WRFF_UNDERFLOW_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT27_8852C_EN SER_DISABLE
// Enable Bit, B_STF_OQT_OVERFLOW_ERR_IMR, B_AX_STF_OQT_OVERFLOW_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT28_8852C_EN SER_ENABLE
// Enable Bit, B_STF_OQT_UNDERFLOW_ERR_IMR, B_AX_STF_OQT_UNDERFLOW_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT29_8852C_EN SER_ENABLE
// Enable Bit, B_REUSE_EN_ERR_IMR, B_AX_REUSE_EN_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT30_8852C_EN SER_DISABLE
// Enable Bit, B_REUSE_SIZE_ERR_IMR, B_AX_REUSE_SIZE_ERR
#define DISPATCHER_DLE_INTERFACE_IMR0_BIT31_8852C_EN SER_DISABLE
/* dle_cpuio 0x18609840 R_AX_CPUIO_ERR_IMR  */
#define DLE_CPUIO_IMR0_MSK_8852C 0x1111
#define DLE_CPUIO_IMR0_SET_8852C 0x1111
// Enable Bit, wde_bufchn_cmd_togl IMR, B_AX_ERR_WDEBUF_OP_ERR
#define DLE_CPUIO_IMR0_BIT0_8852C_EN SER_ENABLE
// Enable Bit, wde_quechn_cmd_togl IMR, B_AX_ERR_WDEQUE_OP_ERR
#define DLE_CPUIO_IMR0_BIT4_8852C_EN SER_ENABLE
// Enable Bit, ple_bufchn_cmd_togl IMR, B_AX_PLEBUF_OP_ERR
#define DLE_CPUIO_IMR0_BIT8_8852C_EN SER_ENABLE
// Enable Bit, pldle_quechn_cmd_togl IMR, B_AX_PLEQUE_OP_ERR
#define DLE_CPUIO_IMR0_BIT12_8852C_EN SER_ENABLE
/* wde_dle 0x18608c38 R_AX_WDE_ERR_IMR  */
#define WDE_DLE_IMR0_MSK_8852C 0x3f0ff3ff
#define WDE_DLE_IMR0_SET_8852C 0x3f0ff3ff
// Enable Bit, r_IMR_ERR_BUFMGN_REQ_QTAID, B_AX_WDE_BUFREQ_QTAID_ERR
#define WDE_DLE_IMR0_BIT0_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_BUFMGN_REQ_SZIS0, B_AX_WDE_BUFREQ_SIZE0_ERR
#define WDE_DLE_IMR0_BIT1_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_BUFMGN_REQ_SZLMT, B_AX_WDE_BUFREQ_SIZELMT_ERR
#define WDE_DLE_IMR0_BIT2_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_BUFMGN_REQ_BUFLACK, B_AX_WDE_BUFREQ_UNAVAL_ERR_V1
#define WDE_DLE_IMR0_BIT3_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_BUFMGN_RTN_IDINVLD, B_AX_WDE_BUFRTN_INVLD_PKTID_ERR_V1
#define WDE_DLE_IMR0_BIT4_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_BUFMGN_RTN_PKTSZ, B_AX_WDE_BUFRTN_SIZE_ERR_V1
#define WDE_DLE_IMR0_BIT5_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_BUFMGN_REQ_SRCHTAIL, B_AX_WDE_BUFREQ_SRCHTAILPG_ERR_V1
#define WDE_DLE_IMR0_BIT6_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_BUFMGN_NPG_STRPG, B_AX_WDE_GETNPG_STRPG_ERR_V1
#define WDE_DLE_IMR0_BIT7_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_BUFMGN_NPG_PGOFST, B_AX_WDE_GETNPG_PGOFST_ERR_V1
#define WDE_DLE_IMR0_BIT8_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_BUFMGN_FRZTO, B_AX_WDE_BUFMGN_FRZTO_ERR_V1
#define WDE_DLE_IMR0_BIT9_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_QUEMGN_CMDTYPE, B_AX_WDE_QUE_CMDTYPE_ERR
#define WDE_DLE_IMR0_BIT12_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_QUEMGN_DSTQINFO, B_AX_WDE_QUE_DSTQUEID_ERR
#define WDE_DLE_IMR0_BIT13_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_QUEMGN_SRCQINFO, B_AX_WDE_QUE_SRCQUEID_ERR
#define WDE_DLE_IMR0_BIT14_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_QUEMGN_PKTCNT_OVRFLW, B_AX_WDE_ENQ_PKTCNT_OVRF_ERR
#define WDE_DLE_IMR0_BIT15_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_QUEMGN_PKTCNT_NEGVAL, B_AX_WDE_ENQ_PKTCNT_NVAL_ERR
#define WDE_DLE_IMR0_BIT16_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_QUEMGN_PREPKTLLT_AD, B_AX_WDE_PREPKTLLT_AD_ERR
#define WDE_DLE_IMR0_BIT17_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_QUEMGN_NXTPKTLL_AD, B_AX_WDE_NXTPKTLL_AD_ERR
#define WDE_DLE_IMR0_BIT18_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_QUEMGN_FRZTO, B_AX_WDE_QUEMGN_FRZTO_ERR
#define WDE_DLE_IMR0_BIT19_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_DATCHN_ARBT, B_AX_WDE_DATCHN_ARBT_ERR
#define WDE_DLE_IMR0_BIT24_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_DATCHN_NULLPG, B_AX_WDE_DATCHN_NULLPG_ERR
#define WDE_DLE_IMR0_BIT25_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_DATCHN_FRZTO, B_AX_WDE_DATCHN_FRZTO_ERR
#define WDE_DLE_IMR0_BIT26_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_DATCHN_RRDY, B_AX_WDE_DATCHN_RRDY_ERR
#define WDE_DLE_IMR0_BIT27_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_DATCHN_ADRERR, B_AX_WDE_DATCHN_ADRERR_ERR
#define WDE_DLE_IMR0_BIT28_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_DATCHN_CAMREQ, B_AX_WDE_DATCHN_CAMREQ_ERR
#define WDE_DLE_IMR0_BIT29_8852C_EN SER_ENABLE
/* ple_dle 0x18609038 R_AX_PLE_ERR_IMR  */
#define PLE_DLE_IMR0_MSK_8852C 0x3f0ff3ff
#define PLE_DLE_IMR0_SET_8852C 0x3f0ff3ff
// Enable Bit, r_IMR_ERR_BUFMGN_REQ_QTAID, B_AX_PLE_BUFREQ_QTAID_ERR
#define PLE_DLE_IMR0_BIT0_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_BUFMGN_REQ_SZIS0, B_AX_PLE_BUFREQ_SIZE0_ERR
#define PLE_DLE_IMR0_BIT1_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_BUFMGN_REQ_SZLMT, B_AX_PLE_BUFREQ_SIZELMT_ERR
#define PLE_DLE_IMR0_BIT2_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_BUFMGN_REQ_BUFLACK, B_AX_PLE_BUFREQ_UNAVAL_ERR_V1
#define PLE_DLE_IMR0_BIT3_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_BUFMGN_RTN_IDINVLD, B_AX_PLE_BUFRTN_INVLD_PKTID_ERR_V1
#define PLE_DLE_IMR0_BIT4_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_BUFMGN_RTN_PKTSZ, B_AX_PLE_BUFRTN_SIZE_ERR_V1
#define PLE_DLE_IMR0_BIT5_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_BUFMGN_REQ_SRCHTAIL, B_AX_PLE_BUFREQ_SRCHTAILPG_ERR_V1
#define PLE_DLE_IMR0_BIT6_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_BUFMGN_NPG_STRPG, B_AX_PLE_GETNPG_STRPG_ERR_V1
#define PLE_DLE_IMR0_BIT7_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_BUFMGN_NPG_PGOFST, B_AX_PLE_GETNPG_PGOFST_ERR_V1
#define PLE_DLE_IMR0_BIT8_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_BUFMGN_FRZTO, B_AX_PLE_BUFMGN_FRZTO_ERR_V1
#define PLE_DLE_IMR0_BIT9_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_QUEMGN_CMDTYPE, B_AX_PLE_QUE_CMDTYPE_ERR
#define PLE_DLE_IMR0_BIT12_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_QUEMGN_DSTQINFO, B_AX_PLE_QUE_DSTQUEID_ERR
#define PLE_DLE_IMR0_BIT13_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_QUEMGN_SRCQINFO, B_AX_PLE_QUE_SRCQUEID_ERR
#define PLE_DLE_IMR0_BIT14_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_QUEMGN_PKTCNT_OVRFLW, B_AX_PLE_ENQ_PKTCNT_OVRF_ERR
#define PLE_DLE_IMR0_BIT15_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_QUEMGN_PKTCNT_NEGVAL, B_AX_PLE_ENQ_PKTCNT_NVAL_ERR
#define PLE_DLE_IMR0_BIT16_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_QUEMGN_PREPKTLLT_AD, B_AX_PLE_PREPKTLLT_AD_ERR
#define PLE_DLE_IMR0_BIT17_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_QUEMGN_NXTPKTLL_AD, B_AX_PLE_NXTPKTLL_AD_ERR
#define PLE_DLE_IMR0_BIT18_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_QUEMGN_FRZTO, B_AX_PLE_QUEMGN_FRZTO_ERR
#define PLE_DLE_IMR0_BIT19_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_DATCHN_ARBT, B_AX_PLE_DATCHN_ARBT_ERR
#define PLE_DLE_IMR0_BIT24_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_DATCHN_NULLPG, B_AX_PLE_DATCHN_NULLPG_ERR
#define PLE_DLE_IMR0_BIT25_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_DATCHN_FRZTO, B_AX_PLE_DATCHN_FRZTO_ERR
#define PLE_DLE_IMR0_BIT26_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_DATCHN_RRDY, B_AX_PLE_DATCHN_RRDY_ERR
#define PLE_DLE_IMR0_BIT27_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_DATCHN_ADRERR, B_AX_PLE_DATCHN_ADRERR_ERR
#define PLE_DLE_IMR0_BIT28_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_DATCHN_CAMREQ, B_AX_PLE_DATCHN_CAMREQ_ERR
#define PLE_DLE_IMR0_BIT29_8852C_EN SER_ENABLE
/* wdrls 0x18609430 R_AX_WDRLS_ERR_IMR  */
#define WDRLS_IMR0_MSK_8852C 0x3337
#define WDRLS_IMR0_SET_8852C 0x3327
// Enable Bit, r_IMR_ERR_CTL_WDPKTID_ISNULL, B_AX_WDRLS_CTL_WDPKTID_ISNULL_ERR
#define WDRLS_IMR0_BIT0_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_CTL_PLPKTID_ISNULL, B_AX_WDRLS_CTL_PLPKTID_ISNULL_ERR
#define WDRLS_IMR0_BIT1_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_CTL_FRZTO, B_AX_WDRLS_CTL_FRZTO_ERR
#define WDRLS_IMR0_BIT2_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_PLEBREQ_TO, B_AX_WDRLS_PLEBREQ_TO_ERR
#define WDRLS_IMR0_BIT4_8852C_EN SER_DISABLE
// Enable Bit, r_IMR_ERR_PLEBREQ_PKTID_ISNULL, B_AX_WDRLS_PLEBREQ_PKTID_ISNULL_ERR
#define WDRLS_IMR0_BIT5_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_RPT0_AGGNUM0, B_AX_WDRLS_RPT0_AGGNUM0_ERR
#define WDRLS_IMR0_BIT8_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_RPT0_FRZTO, B_AX_WDRLS_RPT0_FRZTO_ERR
#define WDRLS_IMR0_BIT9_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_RPT1_AGGNUM0, B_AX_WDRLS_RPT1_AGGNUM_ERR
#define WDRLS_IMR0_BIT12_8852C_EN SER_ENABLE
// Enable Bit, r_IMR_ERR_RPT1_FRZTO, B_AX_WDRLS_RPT1_FRZTO_ERR
#define WDRLS_IMR0_BIT13_8852C_EN SER_ENABLE
/* txpktctl 0x18609f78 R_AX_TXPKTCTL_B0_ERRFLAG_IMR  */
#define TXPKTCTL_IMR0_MSK_8852C 0x350f0f
#define TXPKTCTL_IMR0_SET_8852C 0x350b03
// Enable Bit, r_B0_IMR_ERR_USRCTL_REINIT, B_AX_B0_ISR_ERR_USRCTL_REINIT
#define TXPKTCTL_IMR0_BIT0_8852C_EN SER_ENABLE
// Enable Bit, r_B0_IMR_ERR_USRCTL_NOINIT, B_AX_B0_ISR_ERR_USRCTL_NOINIT
#define TXPKTCTL_IMR0_BIT1_8852C_EN SER_ENABLE
// Enable Bit, r_B0_IMR_ERR_USRCTL_RDNRLSCMD, B_AX_B0_ISR_ERR_USRCTL_RDNRLSCMD
#define TXPKTCTL_IMR0_BIT2_8852C_EN SER_DISABLE
// Enable Bit, r_B0_IMR_ERR_USRCTL_RLSBMPLEN, B_AX_B0_ISR_ERR_USRCTL_RLSBMPLEN
#define TXPKTCTL_IMR0_BIT3_8852C_EN SER_DISABLE
// Enable Bit, r_B0_IMR_ERR_CMDPSR_1STCMDERR, B_AX_B0_ISR_ERR_CMDPSR_1STCMDERR
#define TXPKTCTL_IMR0_BIT8_8852C_EN SER_ENABLE
// Enable Bit, r_B0_IMR_ERR_CMDPSR_CMDTYPE, B_AX_B0_ISR_ERR_CMDPSR_CMDTYPE
#define TXPKTCTL_IMR0_BIT9_8852C_EN SER_ENABLE
// Enable Bit, r_B0_IMR_ERR_CMDPSR_FRZTO, B_AX_B0_ISR_ERR_CMDPSR_FRZTO
#define TXPKTCTL_IMR0_BIT10_8852C_EN SER_DISABLE
// Enable Bit, r_B0_IMR_ERR_CMDPSR_TBLSZ, B_AX_B0_ISR_ERR_CMDPSR_TBLSZ
#define TXPKTCTL_IMR0_BIT11_8852C_EN SER_ENABLE
// Enable Bit, r_B0_IMR_ERR_MPDUINFO_RECFG, B_AX_B0_ISR_ERR_MPDUINFO_RECFG
#define TXPKTCTL_IMR0_BIT16_8852C_EN SER_ENABLE
// Enable Bit, r_B0_IMR_ERR_MPDUIF_DATAERR, B_AX_B0_ISR_ERR_MPDUIF_DATAERR
#define TXPKTCTL_IMR0_BIT18_8852C_EN SER_ENABLE
// Enable Bit, r_B0_IMR_ERR_PRELD_RLSPKTSZERR, B_AX_B0_ISR_ERR_PRELD_RLSPKTSZERR
#define TXPKTCTL_IMR0_BIT20_8852C_EN SER_ENABLE
// Enable Bit, r_B0_IMR_ERR_PRELD_ENTNUMCFG, B_AX_B0_ISR_ERR_PRELD_ENTNUMCFG
#define TXPKTCTL_IMR0_BIT21_8852C_EN SER_ENABLE
/* txpktctl 0x18609fb8 R_AX_TXPKTCTL_B1_ERRFLAG_IMR  */
#define TXPKTCTL_IMR1_MSK_8852C 0x350f0f
#define TXPKTCTL_IMR1_SET_8852C 0x350b03
// Enable Bit, r_B1_IMR_ERR_USRCTL_REINIT, B_AX_B1_ISR_ERR_USRCTL_REINIT
#define TXPKTCTL_IMR1_BIT0_8852C_EN SER_ENABLE
// Enable Bit, r_B1_IMR_ERR_USRCTL_NOINIT, B_AX_B1_ISR_ERR_USRCTL_NOINIT
#define TXPKTCTL_IMR1_BIT1_8852C_EN SER_ENABLE
// Enable Bit, r_B1_IMR_ERR_USRCTL_RDNRLSCMD, B_AX_B1_ISR_ERR_USRCTL_RDNRLSCMD
#define TXPKTCTL_IMR1_BIT2_8852C_EN SER_DISABLE
// Enable Bit, r_B1_IMR_ERR_USRCTL_RLSBMPLEN, B_AX_B1_ISR_ERR_USRCTL_RLSBMPLEN
#define TXPKTCTL_IMR1_BIT3_8852C_EN SER_DISABLE
// Enable Bit, r_B1_IMR_ERR_CMDPSR_1STCMDERR, B_AX_B1_ISR_ERR_CMDPSR_1STCMDERR
#define TXPKTCTL_IMR1_BIT8_8852C_EN SER_ENABLE
// Enable Bit, r_B1_IMR_ERR_CMDPSR_CMDTYPE, B_AX_B1_ISR_ERR_CMDPSR_CMDTYPE
#define TXPKTCTL_IMR1_BIT9_8852C_EN SER_ENABLE
// Enable Bit, r_B1_IMR_ERR_CMDPSR_FRZTO, B_AX_B1_ISR_ERR_CMDPSR_FRZTO
#define TXPKTCTL_IMR1_BIT10_8852C_EN SER_DISABLE
// Enable Bit, r_B1_IMR_ERR_CMDPSR_TBLSZ, B_AX_B1_ISR_ERR_CMDPSR_TBLSZ
#define TXPKTCTL_IMR1_BIT11_8852C_EN SER_ENABLE
// Enable Bit, r_B1_IMR_ERR_MPDUINFO_RECFG, B_AX_B1_ISR_ERR_MPDUINFO_RECFG
#define TXPKTCTL_IMR1_BIT16_8852C_EN SER_ENABLE
// Enable Bit, r_B1_IMR_ERR_MPDUIF_DATAERR, B_AX_B1_ISR_ERR_MPDUIF_DATAERR
#define TXPKTCTL_IMR1_BIT18_8852C_EN SER_ENABLE
// Enable Bit, r_B1_IMR_ERR_PRELD_RLSPKTSZERR, B_AX_B1_ISR_ERR_PRELD_RLSPKTSZERR
#define TXPKTCTL_IMR1_BIT20_8852C_EN SER_ENABLE
// Enable Bit, r_B1_IMR_ERR_PRELD_ENTNUMCFG, B_AX_B1_ISR_ERR_PRELD_ENTNUMCFG
#define TXPKTCTL_IMR1_BIT21_8852C_EN SER_ENABLE
/* bbrpt 0x18609608 R_AX_BBRPT_COM_ERR_IMR  */
#define BBRPT_IMR0_MSK_8852C 0x3
#define BBRPT_IMR0_SET_8852C 0x0
// Enable Bit, r_COM_IMR_ERR_BCHN_REQTO, B_AX_BBRPT_COM_HANG_ISR
#define BBRPT_IMR0_BIT0_8852C_EN SER_DISABLE
// Enable Bit, r_COM_IMR_ERR_BCHN_NULLPLPKTID, B_AX_BBRPT_COM_NULL_PLPKTID_ERR_INT_V1
#define BBRPT_IMR0_BIT1_8852C_EN SER_DISABLE
/* bbrpt 0x18609628 R_AX_BBRPT_CHINFO_ERR_IMR  */
#define BBRPT_IMR1_MSK_8852C 0xff
#define BBRPT_IMR1_SET_8852C 0xff
// Enable Bit, r_CHIF_IMR_ERR_DATA_WAIT, B_AX_BBPRT_CHIF_BB_TO_ERR_V1
#define BBRPT_IMR1_BIT0_8852C_EN SER_ENABLE
// Enable Bit, r_CHIF_IMR_ERR_RPT_OVF, B_AX_BBPRT_CHIF_OVF_ERR_V1
#define BBRPT_IMR1_BIT1_8852C_EN SER_ENABLE
// Enable Bit, r_CHIF_IMR_ERR_DATA_LOSS, B_AX_BBPRT_CHIF_BOVF_ERR_V1
#define BBRPT_IMR1_BIT2_8852C_EN SER_ENABLE
// Enable Bit, r_CHIF_IMR_ERR_HDR_SEGLEN, B_AX_BBPRT_CHIF_HDRL_ERR_V1
#define BBRPT_IMR1_BIT3_8852C_EN SER_ENABLE
// Enable Bit, r_CHIF_IMR_ERR_DATA_BFACT, B_AX_BBPRT_CHIF_LEFT1_ERR_V1
#define BBRPT_IMR1_BIT4_8852C_EN SER_ENABLE
// Enable Bit, r_CHIF_IMR_ERR_DATA_AFACT, B_AX_BBPRT_CHIF_LEFT2_ERR_V1
#define BBRPT_IMR1_BIT5_8852C_EN SER_ENABLE
// Enable Bit, r_CHIF_IMR_ERR_HDR_INVLD, B_AX_BBPRT_CHIF_NULL_ERR_V1
#define BBRPT_IMR1_BIT6_8852C_EN SER_ENABLE
// Enable Bit, r_CHIF_IMR_ERR_GEN_FRZTO, B_AX_BBPRT_CHIF_TO_ERR_V1
#define BBRPT_IMR1_BIT7_8852C_EN SER_ENABLE
/* bbrpt 0x18609638 R_AX_BBRPT_DFS_ERR_IMR  */
#define BBRPT_IMR2_MSK_8852C 0x1
#define BBRPT_IMR2_SET_8852C 0x1
// Enable Bit, r_DFS_IMR_ERR_GEN_FRZTO, B_AX_BBRPT_DFS_TO_ERR_V1
#define BBRPT_IMR2_BIT0_8852C_EN SER_ENABLE
/* bbrpt 0x18609668 R_AX_LA_ERRFLAG_IMR  */
#define BBRPT_IMR3_MSK_8852C 0x1
#define BBRPT_IMR3_SET_8852C 0x1
// Enable Bit, r_LA_IMR_ERR_DATA_LOSS, B_AX_LA_IMR_DATA_LOSS_ERR
#define BBRPT_IMR3_BIT0_8852C_EN SER_ENABLE
/* H_AXIDMA 0x186010b8 R_AX_HAXI_IDCT_MSK  */
#define H_AXIDMA_IMR0_MSK_8852C 0xf
#define H_AXIDMA_IMR0_SET_8852C 0xf
// Enable Bit, txdma_stuck IMR, B_AX_TXMDA_STUCK_IDCT
#define H_AXIDMA_IMR0_BIT0_8852C_EN SER_ENABLE
// Enable Bit, rxdma_stuck IMR, B_AX_RXMDA_STUCK_IDCT
#define H_AXIDMA_IMR0_BIT1_8852C_EN SER_ENABLE
// Enable Bit, txbd_4kbound_lenerr IMR, B_AX__TXBD_4KBOUND_ERR_IDCT
#define H_AXIDMA_IMR0_BIT2_8852C_EN SER_ENABLE
// Enable Bit, txbd_zero_lenerr IMR, B_AX__TXBD_LEN0_ERR_IDCT
#define H_AXIDMA_IMR0_BIT3_8852C_EN SER_ENABLE

#if MAC_AX_USB_SUPPORT
/* H_AXIDMA 0x186010b8 R_AX_HAXI_IDCT_MSK  */
#define H_AXIDMA_IMR0_USB_MSK_8852C 0xf
#define H_AXIDMA_IMR0_USB_SET_8852C 0xd
// Enable Bit, txdma_stuck IMR, B_AX_TXMDA_STUCK_IDCT
#define H_AXIDMA_IMR0_BIT0_8852C_USB_EN SER_ENABLE
// Enable Bit, rxdma_stuck IMR, B_AX_RXMDA_STUCK_IDCT
#define H_AXIDMA_IMR0_BIT1_8852C_USB_EN SER_DISABLE
// Enable Bit, txbd_4kbound_lenerr IMR, B_AX__TXBD_4KBOUND_ERR_IDCT
#define H_AXIDMA_IMR0_BIT2_8852C_USB_EN SER_ENABLE
// Enable Bit, txbd_zero_lenerr IMR, B_AX__TXBD_LEN0_ERR_IDCT
#define H_AXIDMA_IMR0_BIT3_8852C_USB_EN SER_ENABLE
#endif

#if MAC_AX_SDIO_SUPPORT
/* H_AXIDMA 0x186010b8 R_AX_HAXI_IDCT_MSK  */
#define H_AXIDMA_IMR0_SDIO_MSK_8852C 0xf
#define H_AXIDMA_IMR0_SDIO_SET_8852C 0xd
// Enable Bit, txdma_stuck IMR, B_AX_TXMDA_STUCK_IDCT
#define H_AXIDMA_IMR0_BIT0_8852C_SDIO_EN SER_ENABLE
// Enable Bit, rxdma_stuck IMR, B_AX_RXMDA_STUCK_IDCT
#define H_AXIDMA_IMR0_BIT1_8852C_SDIO_EN SER_DISABLE
// Enable Bit, txbd_4kbound_lenerr IMR, B_AX__TXBD_4KBOUND_ERR_IDCT
#define H_AXIDMA_IMR0_BIT2_8852C_SDIO_EN SER_ENABLE
// Enable Bit, txbd_zero_lenerr IMR, B_AX__TXBD_LEN0_ERR_IDCT
#define H_AXIDMA_IMR0_BIT3_8852C_SDIO_EN SER_ENABLE
#endif

u32 ser_imr_config_8852c(struct mac_ax_adapter *adapter, u8 band,
			 enum mac_ax_hwmod_sel sel);

#endif /* #if MAC_AX_8852C_SUPPORT */
#endif
